version: '3.4'

services:
  carepaws.api:
    image: ${DOCKER_REGISTRY-}carepawsapi
    build:
      context: .
      dockerfile: src/CarePaws.API/Dockerfile

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment: 
      POSTGRES_DB: care_paws
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
